### ISSUE TITLE
Raised & lower are swapped

### ISSUE THREAD

**Issue by lizclipse** [babichjacob/async-gate#1]
It looks like the raised/lower methods are swapped - `raise` only lowers the gate and `lower` only raises the gate.

https://github.com/babichjacob/async-gate/blob/1f99fd536a8a6628e9f6afab1638ee3f534b5164/src/lib.rs#L31-L37

https://github.com/babichjacob/async-gate/blob/1f99fd536a8a6628e9f6afab1638ee3f534b5164/src/lib.rs#L51-L57

**Comment by babichjacob** [comment]
Oh wow, thanks for the catch. I'll fix this shortly!

**Comment by babichjacob** [comment]
Thanks for your interest in this project. The fixed version is [published to crates.io](https://crates.io/crates/async-gate) as 0.2.0 (requires manual upgrade from 0.1.4 per semantic versioning).
I'm new to Rust crate development and don't have any tests written for this library so I'd recommend being very skeptical about depending on it. Thanks again.

**Comment by lizclipse** [comment]
No worries, good to see such a quick fix. The alternative you mention in the README seems to be exactly what I was looking for anyway, so it hasn't been a blocker! If I get time, I could look at writing some tests for this and that one if that would help?

**Comment by babichjacob** [comment]
Sure, if that's what you'd like to do! I've added an initial set in cc1fd9cdb0fef984bd47a63fefb7a6a9bf031c19 since stumbling on `tokio-test` made it easier than I expected. Thanks again!
